name: Update badges
on:
  push:
    branches:
      - 'master'
  schedule:
    # Runs at 6am every 7 day
    - cron: "0 6 */7 * *" 
    
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREDLY_USER: karol-szczepek
          #BADGE_SIZE: 85x85
  
